config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  # localhost:3000で一覧画面に遷移させる(#indexまで書かないと遷移しない)
  root "diaries#index"

  # For details on the DSL available within this file, see http:guides.rubyonrails.org/routing.html
  get "/users", to: "users#index"

  # toを省略することも可能
  get "/users/new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/diary.rb
class Diary < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 10_000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]

  # GET /diaries or /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1 or /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: "Diary was successfully created." }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: "Diary was successfully updated." }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy!

    respond_to do |format|
      format.html { redirect_to diaries_path, status: :see_other, notice: "Diary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.expect(diary: [ :title, :body ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # インスタンス変数はビューで使用できる
    @hello = "Hello, World!"

    # ビューがviews/コントローラー名/ビュー名.html.erbならrenderは省略できる
    render template: "users/index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_diary.html.erb
<div id="<%= dom_id diary %>">
  <p>
    <strong>ID:</strong>
    <%= diary.id %>
  </p>

  <p>
    <strong>タイトル:</strong>
    <%= link_to diary.title, diary %>
  </p>

  <p>
    <strong>登録日時:</strong>
    <%= diary.created_at.to_formatted_s %>
  </p>

  <p>
    <strong>更新日時:</strong>
    <%= diary.updated_at.to_formatted_s %>
  </p>
</div>

<%= link_to '日記を新規作成', new_diary_path %>

app/views/diaries/_form.html.erb
<%= form_with(model: diary) do |form| %>
  <% if diary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<% content_for :title, "Editing diary" %>

<h1>Editing diary</h1>

<%= render "form", diary: @diary %>

<br>

<div>
  <%= link_to "Show this diary", @diary %> |
  <%= link_to "Back to diaries", diaries_path %>
</div>

app/views/diaries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Diaries" %>

<h1>日記一覧画面</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>登録日時</th>
      <th>更新日時</th>
    </tr>
  </thead>
  <tbody>
    <% @diaries.each do |diary| %>
      <tr id="<%= dom_id diary %>">
        <td><%= diary.id %></td>
        <td><%= link_to diary.title, diary %></td>
        <td><%= diary.created_at.to_formatted_s %></td>
        <td><%= diary.updated_at.to_formatted_s %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '日記を新規作成', new_diary_path %>

app/views/diaries/new.html.erb
<% content_for :title, "New diary" %>

<h1>New diary</h1>

<%= render "form", diary: @diary %>

<br>

<div>
  <%= link_to "Back to diaries", diaries_path %>
</div>

app/views/diaries/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @diary.id %>
</p>
<p>
  <strong>タイトル:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>本文:</strong>
  <%= @diary.body %>
</p>

<p>
  <strong>登録日時:</strong>
  <%= @diary.created_at.to_formatted_s %>
</p>
<p>
  <strong>更新日時:</strong>
  <%= @diary.updated_at.to_formatted_s %>
</p>

<%= link_to '編集', edit_diary_path(@diary) %> |
<%= link_to '削除', @diary, data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' } %> |
<%= link_to '一覧に戻る', diaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ruby Sample" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header> ヘッダー </header>
    <div>
      <%= yield %>
    </div>
    <footer> フッター </footer>
  </body>
</html>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'application' %>
<%= javascript_import_module_tag 'application' %>
<!--
  コントローラーから受け取った値を表示する
  <%= %>のように=があると実行結果の戻り値を出力
  <% %>で囲むことと戻り値は出力せずRubyコードとして実行できる。 例：<% if @hello.present? %>Hlelo, world!<% end %>
-->
<div class='users-index'><%= @hello %></div>

app/views/users/new.html.erb
<div>Hello, Japan!</div>